var languagedata = {"english": {
        "language_instruction": "Please choose the language you can understand.",
    "reception": "Reception",
        "reception1": "Reception",
        "waiting_room": "Waiting room",
        "consultation_room":"Consultation room",
        "first_time": "Is it your first time?",
        "yes": "Yes",
        "no": "No",
        "yes1": "Yes",
        "no1": "No",
        "self": "Taken a pregnancy test by myself _Yes / No",
        "visit_reason": "Please tell us the reason for your visit today and check all applicable boxes.",
        "absence_period": "Absence of monthly period",
        "nausea": "Feelings of nausea",
        "possible_pregnancy": "Possible pregnancy",
        "inconsistent_period": "Inconsistent period",
        "period_pain": "Stomachache during your period",
        "itching": "Itchiness near the external genitalia",
        "stomach_pain": "Have stomachache",
        "infertility_question": "Want to ask about infertility",
        "other": "Others",
        "question": "medical questionnaire",
        "fill_form_waiting_room": "Please fill out the medical questionnaire in the waiting room.",
        "finished_filling_form": "When you have finished filling out the medical questionnaire, please bring it with you.",
        "take_weight": "Please take your weight, blood pressure, and urine. After that, please wait in the following area until you are called for your examination.",
        "weit_here":"please wait in the following area until you are called for your examination.",        
        "staff_notification": "A member of the staff will inform you where you should go.",
        "call_order": "Your (name/number) will be called in a first_come, first_serve basis.",
        "call_order2":"*Depending on the circumstances, there are cases the order may be changed.",    
        "medicines": "medicines",
        "give_medicines_in_hospital":"We will give you your medicines in this hospital after your examination.",
        "give_medicines_out_of_hospital":">We cannot provide you with medicines here. We will give you a prescription and you can buy the medicines in a pharmacy outside the hospital.",
        "prescription_validity": "The validity of the prescription is  [   ]  days from the issued date.",
        "payment_instructions_machine": "Please pay your bill at the automated accounting machine.",
        "payment_instructions_cashier": "Please pay your bill at the cashier counter."
    },
    "japanese": {
        // Japanese translations for each key
    },
    "chinese": {
       "language_instruction": "请选择您可以理解的语言。",
        "reception": "挂号",
    "reception1": "挂号",
    "waiting_room": "候诊室",
    "consultation_room": "诊室",
    "first_time": "这是您第一次来吗？",
    "yes": "是",
    "no": "否",
    "yes1": "是",
    "no1": "否",
    "self": "我是否已自行进行了怀孕测试 _ 是 / 否",
    "visit_reason": "请告诉我们您今天来就诊的原因，并勾选所有适用的选项。",
    "absence_period": "月经停止",
    "nausea": "恶心的感觉",
    "possible_pregnancy": "可能怀孕",
    "inconsistent_period": "月经不规律",
    "period_pain": "月经期间腹痛",
    "itching": "外阴瘙痒",
    "stomach_pain": "腹痛",
    "infertility_question": "想咨询不孕问题",
    "other": "其他",
    "question": "健康问卷",
    "fill_form_waiting_room": "请在候诊室填写健康问卷。",
    "finished_filling_form": "完成填写后，请将问卷带过来。",
    "take_weight": "请测量您的体重、血压和尿液。之后，请在以下区域等候，直到叫到您的名字。",
    "weit_here": "请在以下区域等候，直到叫到您的名字。",
    "staff_notification": "工作人员会告知您需要去哪里。",
    "call_order": "您的（姓名/编号）将按先到先服务的顺序叫号。",
    "call_order2": "*根据情况，顺序可能会有所调整。",
    "medicines": "药物",
    "give_medicines_in_hospital": "我们将在您检查后在院内提供药物。",
    "give_medicines_out_of_hospital": "我们无法在这里提供药物。我们将给您开处方，您可以在院外的药房购买药物。",
    "prescription_validity": "处方的有效期自签发日起 [   ] 天。",
    "payment_instructions_machine": "请在自动结算机上支付账单。",
    "payment_instructions_cashier": "请在收银台支付账单。"
    ,"card":"我们会给您一张就诊卡。请下次在接待处出示。"},
    "filipino": {
        "language_instruction": "Piliin ang wikang iyong naiintindihan.",
        "reception": "Pagpaparehistro",
        "reception1": "Pagpaparehistro",
        "waiting_room": "Silid Paghihintay",
        "consultation_room": "Silid Konsultasyon",
        "first_time": "Ito ba ang iyong unang pagkakataon?",
        "yes": "Oo",
        "no": "Hindi",
        "yes1": "Oo",
        "no1": "Hindi",
        "self": "Nagsagawa na ng pagsusuri sa pagbubuntis nang mag_isa _Oo / Hindi",
        "visit_reason": "Sabihin sa amin ang dahilan ng iyong pagbisita ngayon at lagyan ng tsek ang lahat ng naaangkop na kahon.",
        "absence_period": "Pagkawala ng buwanang regla",
        "nausea": "Pakiramdam ng pagsusuka",
        "possible_pregnancy": "Posibleng pagbubuntis",
        "inconsistent_period": "Hindi regular na regla",
        "period_pain": "Sakit sa tiyan tuwing regla",
        "itching": "Pangangati malapit sa panlabas na bahagi ng genitalia",
        "stomach_pain": "May sakit sa tiyan",
        "infertility_question": "Nais magtanong tungkol sa kawalan ng kakayahan na magkaanak",
        "other": "Iba pa",
        "question": "Medikal na Talatanungan",
        "fill_form_waiting_room": "Pakisagutan ang medikal na talatanungan sa silid paghihintay.",
        "finished_filling_form": "Kapag tapos mo nang sagutan ang medikal na talatanungan, pakidala ito sa amin.",
        "take_weight": "Pakisukat ang iyong timbang, presyon ng dugo, at ihi. Pagkatapos nito, maghintay sa sumusunod na lugar hanggang sa ikaw ay tawagin para sa pagsusuri.",
        "weit_here": "Pakihintay sa sumusunod na lugar hanggang sa ikaw ay tawagin para sa pagsusuri.",
        "staff_notification": "Ipapaalam sa iyo ng isang tauhan kung saan ka dapat pumunta.",
        "call_order": "Ang iyong (pangalan / numero) ay tatawagin ayon sa pagkakasunud_sunod ng pagdating.",
        "call_order2": "*Depende sa sitwasyon, may mga pagkakataong maaaring magbago ang pagkakasunud_sunod.",
        "medicines": "Mga gamot",
        "give_medicines_in_hospital": "Ibibigay namin ang iyong mga gamot sa ospital na ito pagkatapos ng iyong pagsusuri.",
        "give_medicines_out_of_hospital": "Hindi kami makakapagbigay ng mga gamot dito. Bibigyan ka namin ng reseta at maaari mong bilhin ang mga gamot sa botika sa labas ng ospital.",
        "prescription_validity": "Ang bisa ng reseta ay [   ] araw mula sa petsa ng pagkakabigay.",
        "payment_instructions_machine": "Paki_bayad ang iyong bayarin sa automated na makina para sa bayad.",
        "payment_instructions_cashier": "Paki_bayad ang iyong bayarin sa counter ng kahera."
    ,"card":"Ibibigay namin sa inyo ang inyong patient ID card. Pakipakita ito sa reception sa susunod na pagpunta."},
    "korean": {
        "language_instruction": "이해할 수 있는 언어를 선택해 주세요.",
        "reception": "접수",
        "reception1": "접수",
        "waiting_room": "대기실",
        "consultation_room": "진료실",
        "first_time": "처음 방문하셨나요?",
        "yes": "네",
        "no": "아니요",
        "yes1": "네",
        "no1": "아니요",
        "self": "임신 테스트를 스스로 했습니다 _ 예 / 아니요",
        "visit_reason": "오늘 방문 이유를 알려주시고 해당하는 모든 항목에 체크해 주세요.",
        "absence_period": "생리가 중단됨",
        "nausea": "메스꺼움 느낌",
        "possible_pregnancy": "임신 가능성 있음",
        "inconsistent_period": "생리 불규칙",
        "period_pain": "생리 중 복통",
        "itching": "외음부 가려움",
        "stomach_pain": "복통이 있음",
        "infertility_question": "불임에 대해 문의하고 싶음",
        "other": "기타",
        "question": "의료 설문지",
        "fill_form_waiting_room": "대기실에서 의료 설문지를 작성해 주세요.",
        "finished_filling_form": "의료 설문지 작성을 완료하시면 제출해 주세요.",
        "take_weight": "체중, 혈압, 소변을 측정해 주세요. 이후 진료 호출 시까지 다음 장소에서 대기해 주세요.",
        "weit_here": "진료 호출 시까지 다음 장소에서 대기해 주세요.",
        "staff_notification": "직원이 어디로 가야 할지 안내해 드립니다.",
        "call_order": "(이름/번호)는 접수 순서대로 호출됩니다.",
        "call_order2": "*상황에 따라 순서가 변경될 수 있습니다.",
        "medicines": "약",
        "give_medicines_in_hospital": "진료 후 병원 내에서 약을 드리겠습니다.",
        "give_medicines_out_of_hospital": "여기서는 약을 제공하지 않습니다. 처방전을 드리니 외부 약국에서 구매해 주세요.",
        "prescription_validity": "처방전의 유효기간은 발급일로부터 [   ]일입니다.",
        "payment_instructions_machine": "자동 결제 기기에서 결제해 주세요.",
        "payment_instructions_cashier": "계산대에서 결제해 주세요.",
        "card":"진찰권을 드리겠습니다. 다음부터는 접수에 제출해 주세요.",
    },
    "portuguese": {
        "language_instruction": "Por favor, escolha o idioma que você entende.",
        "reception": "Recepção",
        "reception1": "Recepção",
        "waiting_room": "Sala de espera",
        "consultation_room": "Sala de consulta",
        "first_time": "É a sua primeira vez?",
        "yes": "Sim",
        "no": "Não",
        "yes1": "Sim",
        "no1": "Não",
        "self": "Fiz um teste de gravidez por conta própria _ Sim / Não",
        "visit_reason": "Por favor, diga_nos o motivo da sua visita hoje e marque todas as opções aplicáveis.",
        "absence_period": "Ausência de menstruação",
        "nausea": "Sensação de náusea",
        "possible_pregnancy": "Possível gravidez",
        "inconsistent_period": "Menstruação irregular",
        "period_pain": "Dor abdominal durante a menstruação",
        "itching": "Coceira na área genital externa",
        "stomach_pain": "Dor de estômago",
        "infertility_question": "Quero perguntar sobre infertilidade",
        "other": "Outros",
        "question": "questionário médico",
        "fill_form_waiting_room": "Por favor, preencha o questionário médico na sala de espera.",
        "finished_filling_form": "Quando terminar de preencher o questionário médico, por favor, traga_o com você.",
        "take_weight": "Por favor, meça seu peso, pressão arterial e urina. Depois disso, aguarde na área indicada até ser chamado para a consulta.",
        "weit_here": "Por favor, aguarde na área indicada até ser chamado para a consulta.",
        "staff_notification": "Um membro da equipe informará onde você deve ir.",
        "call_order": "Seu (nome/número) será chamado em ordem de chegada.",
        "call_order2": "*Dependendo das circunstâncias, a ordem pode ser alterada.",
        "medicines": "medicamentos",
        "give_medicines_in_hospital": "Daremos seus medicamentos neste hospital após a consulta.",
        "give_medicines_out_of_hospital": "Não podemos fornecer medicamentos aqui. Daremos uma receita e você poderá comprar os medicamentos em uma farmácia fora do hospital.",
        "prescription_validity": "A validade da receita é de [   ] dias a partir da data de emissão.",
        "payment_instructions_machine": "Por favor, pague sua conta na máquina de pagamento automatizado.",
        "payment_instructions_cashier": "Por favor, pague sua conta no balcão do caixa.",
        "card":"Vamos lhe entregar um cartão de identificação do paciente. Por favor, apresente-o na recepção na próxima vez."
    },
    "russian": {
        "language_instruction": "Пожалуйста, выберите язык, который вы понимаете.",
        "reception": "Регистрация",
        "reception1": "Регистрация",
        "waiting_room": "Зал ожидания",
        "consultation_room": "Консультационный кабинет",
        "first_time": "Вы здесь впервые?",
        "yes": "Да",
        "no": "Нет",
        "yes1": "Да",
        "no1": "Нет",
        "self": "Проведен тест на беременность самостоятельно _ Да / Нет",
        "visit_reason": "Пожалуйста, укажите причину вашего визита сегодня и отметьте все подходящие пункты.",
        "absence_period": "Отсутствие месячных",
        "nausea": "Чувство тошноты",
        "possible_pregnancy": "Возможная беременность",
        "inconsistent_period": "Нерегулярный цикл",
        "period_pain": "Боль в животе во время месячных",
        "itching": "Зуд в области наружных половых органов",
        "stomach_pain": "Боль в животе",
        "infertility_question": "Хочу задать вопрос о бесплодии",
        "other": "Другие",
        "question": "медицинская анкета",
        "fill_form_waiting_room": "Пожалуйста, заполните медицинскую анкету в зале ожидания.",
        "finished_filling_form": "Когда заполните медицинскую анкету, пожалуйста, принесите её с собой.",
        "take_weight": "Пожалуйста, измерьте вес, артериальное давление и сдайте мочу. После этого подождите в указанной зоне до вызова на приём.",
        "weit_here": "Пожалуйста, подождите в указанной зоне до вызова на приём.",
        "staff_notification": "Сотрудник сообщит вам, куда нужно пройти.",
        "call_order": "Ваше (имя/номер) будет вызвано в порядке очереди.",
        "call_order2": "*В зависимости от обстоятельств порядок очереди может быть изменён.",
        "medicines": "лекарства",
        "give_medicines_in_hospital": "Мы выдадим вам лекарства в этой больнице после приёма.",
        "give_medicines_out_of_hospital": "Мы не можем предоставить вам лекарства здесь. Мы выпишем рецепт, и вы сможете приобрести лекарства в аптеке за пределами больницы.",
        "prescription_validity": "Срок действия рецепта составляет [   ] дней с даты выдачи.",
        "payment_instructions_machine": "Пожалуйста, оплатите счёт в автомате для оплаты.",
        "payment_instructions_cashier": "Пожалуйста, оплатите счёт на кассе.",
        "card":"Мы выдадим вам карточку пациента. Пожалуйста, предъявите её на стойке регистрации в следующий раз."
    },
    "indonesian":{
        "language_instruction": "Silakan pilih bahasa yang Anda pahami.",
        "reception": "Pendaftaran",
        "reception1": "Pendaftaran",
        "waiting_room": "Ruang tunggu",
        "consultation_room": "Ruang konsultasi",
        "first_time": "Apakah ini pertama kali Anda?",
        "yes": "Ya",
        "no": "Tidak",
        "yes1": "Ya",
        "no1": "Tidak",
        "self": "Saya melakukan tes kehamilan sendiri _ Ya / Tidak",
        "visit_reason": "Silakan beri tahu kami alasan kunjungan Anda hari ini dan centang semua kotak yang sesuai.",
        "absence_period": "Tidak ada menstruasi bulanan",
        "nausea": "Merasa mual",
        "possible_pregnancy": "Kemungkinan hamil",
        "inconsistent_period": "Menstruasi tidak teratur",
        "period_pain": "Sakit perut selama menstruasi",
        "itching": "Gatal di area genital luar",
        "stomach_pain": "Sakit perut",
        "infertility_question": "Ingin bertanya tentang ketidaksuburan",
        "other": "Lainnya",
        "question": "kuesioner medis",
        "fill_form_waiting_room": "Silakan isi kuesioner medis di ruang tunggu.",
        "finished_filling_form": "Setelah selesai mengisi kuesioner medis, silakan bawa bersama Anda.",
        "take_weight": "Silakan ukur berat badan, tekanan darah, dan urine Anda. Setelah itu, silakan tunggu di area berikut hingga Anda dipanggil untuk pemeriksaan.",
        "weit_here": "Silakan tunggu di area berikut hingga Anda dipanggil untuk pemeriksaan.",
        "staff_notification": "Anggota staf akan memberitahu Anda ke mana harus pergi.",
        "call_order": "(Nama/nomor) Anda akan dipanggil berdasarkan urutan kedatangan.",
        "call_order2": "*Tergantung pada situasi, urutan panggilan mungkin berubah.",
        "medicines": "obat_obatan",
        "give_medicines_in_hospital": "Kami akan memberikan obat Anda di rumah sakit ini setelah pemeriksaan.",
        "give_medicines_out_of_hospital": "Kami tidak dapat menyediakan obat di sini. Kami akan memberikan resep dan Anda dapat membeli obat di apotek di luar rumah sakit.",
        "prescription_validity": "Masa berlaku resep adalah [   ] hari sejak tanggal penerbitan.",
        "payment_instructions_machine": "Silakan bayar tagihan Anda di mesin pembayaran otomatis.",
        "payment_instructions_cashier": "Silakan bayar tagihan Anda di kasir."
    ,"card":"Kami akan memberikan kartu identifikasi pasien. Silakan tunjukkan kartu tersebut di resepsi pada kunjungan berikutnya."}
    // Add other languages similarly
}
